sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install coveralls
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      npm run sauce
    fi
